blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/komunite/tezgah/discussions
    about: Ask a question in Discussions if this is not a bug or feature request.
